backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /public

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "trips"
    label: "Wyjazdy"
    folder: "src/pages/our-trips"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "new-trip"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Data wyjazdu", name: "date", widget: "date"}
      - {label: "Miejsce wyjazdu", name: "place", widget: "string"}
      - {label: "Krótki Opis", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "select", options: ["newTrip","finishedTrip"]}

  - name: "pages"
    label: "Strona WWW"
    files:
      - file: "src/pages/main/index.md"
        label: "Main Page"
        name: "main"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: jumbotrone, name: jumbotrone, widget: object, fields: [{label: title, name: title, widget: string}, {label: description, name: description, widget: text}]}
          - {label: Ebook, name: ebook, widget: file,  default: "/ebook"}
          - {label: Opis, name: description, widget: text}
          - {label: Treść, name: "body", widget: markdown}